# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
    - "3.5"
    - "3.6"
    - "pypy3.5"
matrix:
    include:
        - python: 3.7
          dist: xenial

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - "pip install coveralls"

# command to run tests, e.g. python setup.py test
script: make ci
after_success: coveralls
